export const ADD_PRODUCT = "ADD_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"

export const SELECT_ADDRESS = "SELECT_ADDRESS"
export const SELECT_ADDRESS_CLEANUP = "SELECT_ADDRESS_CLEANUP"


