export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const GET_USER_ADDRESS = "GET_USER_ADDRESS"
export const SET_USER_ADDRESS = "SET_USER_ADDRESS"
export const GET_USER_ORDERS = "GET_USER_ORDERS"
export const SET_USER_ORDER = "SET_USER_ORDER"

export const GET_USER_ADDRESS_ERROR = "GET_USER_ADDRESS_ERROR"
export const SET_USER_ADDRESS_ERROR = "SET_USER_ADDRESS_ERROR"
export const GET_USER_DETAILS_ERROR = "GET_USER_DETAILS_ERROR"
export const GET_USER_ORDERS_ERROR = "GET_USER_ORDERS_ERROR"
export const SET_USER_ORDER_ERROR = "SET_USER_ORDER_ERROR"
export const SET_USER_ORDER_CLEANUP = "SET_USER_ORDER_CLEANUP"

export const GET_USER_ORDERS_CLEANUP = "GET_USER_ORDERS_CLEANUP"