export const HANDLE_SIGNIN = "HANDLE_SIGNIN"
export const HANDE_SIGNOUT = "HANDLE_SIGNOUT"
export const HANDLE_SIGNUP = "HANDLE_SIGNUP"
export const HANDLE_SIGNIN_ERROR = "HANDLE_SIGNIN_ERROR"
export const HANDLE_SIGNUP_ERROR = "HANDLE_SIGNUP_ERROR"

export const HANDLE_TOKEN_ID = "HANDLE_TOKEN_ID"